# mkdir -p ./IND-JLMIV+R-1Y-arff-nominalLabel-result
# mkdir -p ./MA-SZZ-2020-arff-nominalLabel-result
bin/CLAMI -f ./IND-JLMIV+R-1Y/ant-ivy-1.4.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/ant-ivy-1.4.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/ant-ivy-2.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/ant-ivy-2.0.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/ant-ivy-2.2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/ant-ivy-2.2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/ant-ivy-2.3.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/ant-ivy-2.3.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/ant-ivy-2.4.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/ant-ivy-2.4.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/archiva-1.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/archiva-1.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/archiva-1.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/archiva-1.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/archiva-2.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/archiva-2.0.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/calcite-1.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/calcite-1.0.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/calcite-1.12.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/calcite-1.12.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/calcite-1.7.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/calcite-1.7.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/cayenne-3.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/cayenne-3.0.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/cayenne-3.1.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/cayenne-3.1.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-bcel-6.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-bcel-6.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-bcel-6.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-bcel-6.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-beanutils-1.7.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-beanutils-1.7.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-beanutils-1.8.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-beanutils-1.8.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-codec-1.8_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-codec-1.8_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-collections-3.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-collections-3.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-collections-3.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-collections-3.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-collections-3.3_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-collections-3.3_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-collections-4.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-collections-4.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-compress-1.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-compress-1.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-compress-1.11_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-compress-1.11_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-compress-1.14_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-compress-1.14_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-compress-1.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-compress-1.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-compress-1.3_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-compress-1.3_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-compress-1.5_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-compress-1.5_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-compress-1.9_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-compress-1.9_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-configuration-1.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-configuration-1.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-configuration-1.10_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-configuration-1.10_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-configuration-1.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-configuration-1.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-configuration-1.4_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-configuration-1.4_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-configuration-1.6_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-configuration-1.6_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-configuration-1.7_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-configuration-1.7_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-configuration-2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-configuration-2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-configuration-2.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-configuration-2.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-dbcp-1.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-dbcp-1.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-dbcp-1.3_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-dbcp-1.3_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-dbcp-2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-dbcp-2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-digester-3.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-digester-3.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-io-1.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-io-1.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-io-1.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-io-1.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-io-1.3_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-io-1.3_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-io-2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-io-2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-io-2.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-io-2.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-jcs-1.3_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-jcs-1.3_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-jcs-2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-jcs-2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-jexl-2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-jexl-2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-jexl-2.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-jexl-2.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-lang-2.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-lang-2.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-lang-2.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-lang-2.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-lang-2.4_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-lang-2.4_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-lang-2.5_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-lang-2.5_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-lang-3.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-lang-3.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-lang-3.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-lang-3.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-lang-3.4_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-lang-3.4_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-lang-3.5_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-lang-3.5_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-math-1.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-math-1.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-math-1.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-math-1.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-math-1.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-math-1.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-math-2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-math-2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-math-2.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-math-2.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-math-3.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-math-3.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-math-3.3_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-math-3.3_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-net-1.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-net-1.0.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-net-1.2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-net-1.2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-net-1.4.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-net-1.4.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-net-2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-net-2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-net-2.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-net-2.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-net-3.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-net-3.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-net-3.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-net-3.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-net-3.4_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-net-3.4_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-scxml-0.5_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-scxml-0.5_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-scxml-0.7_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-scxml-0.7_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-validator-1.2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-validator-1.2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-validator-1.4.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-validator-1.4.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-vfs-1.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-vfs-1.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/commons-vfs-2.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/commons-vfs-2.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/deltaspike-0.4_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/deltaspike-0.4_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/deltaspike-1.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/deltaspike-1.0.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/deltaspike-1.5.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/deltaspike-1.5.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/deltaspike-1.8.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/deltaspike-1.8.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/eagle-0.3.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/eagle-0.3.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/giraph-1.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/giraph-1.0.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/giraph-1.1.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/giraph-1.1.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/gora-0.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/gora-0.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/gora-0.2_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/gora-0.2_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/gora-0.3_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/gora-0.3_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/gora-0.5_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/gora-0.5_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/jspwiki-2.4.56_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/jspwiki-2.4.56_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/jspwiki-2.6.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/jspwiki-2.6.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/knox-0.11.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/knox-0.11.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/knox-0.3.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/knox-0.3.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/knox-0.5.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/knox-0.5.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/knox-0.7.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/knox-0.7.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/knox-1.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/knox-1.0.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/kylin-0.6.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/kylin-0.6.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/kylin-1.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/kylin-1.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/kylin-1.6.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/kylin-1.6.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/lens-2.6.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/lens-2.6.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/mahout-0.10.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/mahout-0.10.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/mahout-0.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/mahout-0.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/mahout-0.4_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/mahout-0.4_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/mahout-0.6_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/mahout-0.6_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/mahout-0.8_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/mahout-0.8_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/manifoldcf-0.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/manifoldcf-0.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/manifoldcf-0.4_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/manifoldcf-0.4_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/manifoldcf-1.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/manifoldcf-1.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/manifoldcf-1.5_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/manifoldcf-1.5_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/manifoldcf-1.9_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/manifoldcf-1.9_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/manifoldcf-2.5_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/manifoldcf-2.5_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/manifoldcf-2.9_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/manifoldcf-2.9_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/nutch-0.7_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/nutch-0.7_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/nutch-0.9_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/nutch-0.9_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/nutch-1.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/nutch-1.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/nutch-1.10_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/nutch-1.10_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/nutch-1.12_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/nutch-1.12_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/nutch-1.14_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/nutch-1.14_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/nutch-1.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/nutch-1.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/nutch-1.3_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/nutch-1.3_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/nutch-1.6_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/nutch-1.6_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/nutch-1.8_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/nutch-1.8_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/opennlp-1.7.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/opennlp-1.7.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/parquet-mr-1.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/parquet-mr-1.0.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/parquet-mr-1.6.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/parquet-mr-1.6.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/parquet-mr-1.9.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/parquet-mr-1.9.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/santuario-java-1.5.9_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/santuario-java-1.5.9_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/santuario-java-2.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/santuario-java-2.0.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/systemml-0.13_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/systemml-0.13_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/systemml-0.9_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/systemml-0.9_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/systemml-1.1.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/systemml-1.1.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/tika-0.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/tika-0.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/tika-0.5_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/tika-0.5_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/tika-0.9_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/tika-0.9_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/tika-1.10_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/tika-1.10_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/tika-1.14_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/tika-1.14_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/tika-1.17_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/tika-1.17_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/tika-1.1_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/tika-1.1_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/tika-1.3_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/tika-1.3_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/tika-1.5_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/tika-1.5_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/wss4j-1.5.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/wss4j-1.5.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/wss4j-1.6.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/wss4j-1.6.0_aggregated.csv 
bin/CLAMI -f ./IND-JLMIV+R-1Y/wss4j-2.0.0_aggregated.arff  -l bug -p 1 > ./IND-JLMIV+R-1Y-arff-nominalLabel-result/wss4j-2.0.0_aggregated.csv 
bin/CLAMI -f ./MA-SZZ-2020/flume-1.2.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/flume-1.2.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/flume-1.3.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/flume-1.3.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/flume-1.3.1.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/flume-1.3.1.csv 
bin/CLAMI -f ./MA-SZZ-2020/flume-1.4.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/flume-1.4.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/flume-1.5.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/flume-1.5.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/flume-1.5.1.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/flume-1.5.1.csv 
bin/CLAMI -f ./MA-SZZ-2020/flume-1.5.2.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/flume-1.5.2.csv 
bin/CLAMI -f ./MA-SZZ-2020/flume-1.6.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/flume-1.6.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/flume-1.7.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/flume-1.7.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/flume-1.8.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/flume-1.8.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/mahout-0.10.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/mahout-0.10.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/mahout-0.11.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/mahout-0.11.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/mahout-0.12.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/mahout-0.12.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/mahout-0.13.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/mahout-0.13.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/mahout-0.4.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/mahout-0.4.csv 
bin/CLAMI -f ./MA-SZZ-2020/mahout-0.5.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/mahout-0.5.csv 
bin/CLAMI -f ./MA-SZZ-2020/mahout-0.6.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/mahout-0.6.csv 
bin/CLAMI -f ./MA-SZZ-2020/mahout-0.7.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/mahout-0.7.csv 
bin/CLAMI -f ./MA-SZZ-2020/mahout-0.8.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/mahout-0.8.csv 
bin/CLAMI -f ./MA-SZZ-2020/mahout-0.9.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/mahout-0.9.csv 
bin/CLAMI -f ./MA-SZZ-2020/maven-2.2.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/maven-2.2.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/maven-2.2.1.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/maven-2.2.1.csv 
bin/CLAMI -f ./MA-SZZ-2020/maven-3.0.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/maven-3.0.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/maven-3.0.1.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/maven-3.0.1.csv 
bin/CLAMI -f ./MA-SZZ-2020/maven-3.0.2.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/maven-3.0.2.csv 
bin/CLAMI -f ./MA-SZZ-2020/maven-3.0.3.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/maven-3.0.3.csv 
bin/CLAMI -f ./MA-SZZ-2020/maven-3.0.4.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/maven-3.0.4.csv 
bin/CLAMI -f ./MA-SZZ-2020/maven-3.0.5.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/maven-3.0.5.csv 
bin/CLAMI -f ./MA-SZZ-2020/maven-3.1.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/maven-3.1.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/maven-3.1.1.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/maven-3.1.1.csv 
bin/CLAMI -f ./MA-SZZ-2020/shiro-1.1.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/shiro-1.1.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/shiro-1.2.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/shiro-1.2.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/shiro-1.2.1.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/shiro-1.2.1.csv 
bin/CLAMI -f ./MA-SZZ-2020/shiro-1.2.2.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/shiro-1.2.2.csv 
bin/CLAMI -f ./MA-SZZ-2020/shiro-1.2.3.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/shiro-1.2.3.csv 
bin/CLAMI -f ./MA-SZZ-2020/shiro-1.2.4.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/shiro-1.2.4.csv 
bin/CLAMI -f ./MA-SZZ-2020/shiro-1.2.5.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/shiro-1.2.5.csv 
bin/CLAMI -f ./MA-SZZ-2020/shiro-1.2.6.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/shiro-1.2.6.csv 
bin/CLAMI -f ./MA-SZZ-2020/shiro-1.3.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/shiro-1.3.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/shiro-1.3.1.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/shiro-1.3.1.csv 
bin/CLAMI -f ./MA-SZZ-2020/zeppelin-0.5.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/zeppelin-0.5.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/zeppelin-0.5.5.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/zeppelin-0.5.5.csv 
bin/CLAMI -f ./MA-SZZ-2020/zeppelin-0.5.6.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/zeppelin-0.5.6.csv 
bin/CLAMI -f ./MA-SZZ-2020/zeppelin-0.6.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/zeppelin-0.6.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/zeppelin-0.6.1.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/zeppelin-0.6.1.csv 
bin/CLAMI -f ./MA-SZZ-2020/zeppelin-0.6.2.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/zeppelin-0.6.2.csv 
bin/CLAMI -f ./MA-SZZ-2020/zeppelin-0.7.0.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/zeppelin-0.7.0.csv 
bin/CLAMI -f ./MA-SZZ-2020/zeppelin-0.7.1.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/zeppelin-0.7.1.csv 
bin/CLAMI -f ./MA-SZZ-2020/zeppelin-0.7.2.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/zeppelin-0.7.2.csv 
bin/CLAMI -f ./MA-SZZ-2020/zeppelin-0.7.3.arff  -l bug -p 1 > ./MA-SZZ-2020-arff-nominalLabel-result/zeppelin-0.7.3.csv 
